FROM golang:1.22-alpine AS builder 
WORKDIR /app

COPY . .

RUN go build -o server server.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .

RUN apk add --no-cache ca-certificates

ENV PORT=8080
EXPOSE 8080

CMD [./server]


